name: sis_progress
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1
  flutter_svg: ^1.1.6
  percent_indicator: ^4.0.1
  custom_check_box: ^0.0.4
  dropdown_button2: ^1.9.2
  syncfusion_flutter_charts: ^20.4.38
  watcher: ^1.0.2
  shared_preferences: ^2.0.16
  dropdownfield: ^1.0.3
  dropdown_textfield: ^1.0.7
  table_calendar: ^3.0.8
  image_picker: ^0.8.6
  intl: ^0.17.0
  dio: ^4.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/logo.svg
    - assets/logo.png
    - assets/previous.png
    - assets/Rectangle 1114.png
    - assets/Vectorchevorn.png
    - assets/Vector.svg
    - assets/Calendar.svg
    - assets/Calendar.png
    - assets/svgviewer-output.svg
    - assets/Rocket (2).svg
    - assets/Test.svg
    - assets/yyy.png
  