name: sis_progress
description: Ankap Project.

publish_to: 'none'

version: 1.0.1+25

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_launcher_icons: "^0.11.0"
  dartx: ^1.1.0
  google_fonts: ^3.0.1
  animated_splash_screen: ^1.3.0
  flutter_svg: ^1.1.6
  percent_indicator: ^4.0.1
  custom_check_box: ^0.0.4
  syncfusion_flutter_charts: ^20.4.38
  flutter_verification_code: ^1.1.6
  shared_preferences: ^2.0.16
  table_calendar: ^3.0.8
  image_picker: ^0.8.6
  uni_links: ^0.5.1
  intl_phone_number_input: ^0.7.0
  intl: ^0.17.0
  dio: ^4.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/Logo.svg
    - assets/logo.png
    - assets/previous.png
    - assets/Rectangle 1114.png
    - assets/Vectorchevorn.png
    - assets/Vector.svg
    - assets/Calendar.svg
    - assets/Calendar.png
    - assets/Rocket (2).svg
    - assets/Test.svg
    - assets/yyy.png
    - assets/Books.png
    - assets/Target.png
    - assets/Cal.png
    - assets/Subtask.png
    - assets/MyPoints.png
    - assets/Info.png
    - assets/Tooltip.svg
    - assets/Camera.svg
    - assets/Greyquest.svg
    - assets/AvatarAvatar.png
    - assets/Smile.png
    - assets/Happy.png
    - assets/Good.png
    - assets/Sad.png
    - assets/VectorChevron.svg
    - assets/Home.png
    - assets/NavCal.png
    - assets/Tasks.png
    - assets/Checklist.png
    - assets/Profile.png
    - assets/List.svg
    - assets/Connection.svg
    - assets/Group 2218.png
