class Universities {
  final List<String> universities = [
  "Stanford University",
  "Yale University",
  "Duke University",
  "Princeton University",
  "Dartmouth University",
  "Columbia University",
  "University of Chicago",
  "Harvard University",
  "Johns Hopkins University",
  "University of Pennsylvania",
  "Grinnell College"
  ];

  final List<List<String>> points = [
    ["1510", "1560", "1601+"],
    ["1515", "1565", "1601+"],
    ["1460", "1510", "1570"],
    ["1520", "1570", "1601+"],
    ["1480", "1530", "1590"],
    ["1510", "1560", "1601+"],
    ["1490", "1540", "1601+"],
    ["1520", "1570", "1601+"],
    ["1515", "1565", "1601+"],
    ["1490", "1540", "1590"],
    ["1350", "1380", "1420"]];

  final List<String> schools = [    'Phillips Academy Andover',
    'Phillips Exeter Academy',    'The Hotchkiss School',
    'Choate Rosemary Hall',    'Groton School',
    'The Lawrenceville School',    'St. Paul’s School',
    'Noble and Greenough School',    'Deerfield Academy',
    'Princeton International School',    'The Loomis Chaffee School',
    'Concord Academy',    'Milton Academy',
    'Cate School',
    'Middlesex School',    'The Thacher School',
    "St. Mark's School",    'Lake Forest Academy',
    'Cranbrook Schools',    'American Heritage Schools',
    'Harvard-Westlake School',    'Chapin School',
    'The Dalton School',    'The Winsor School',
    'The Spence School',    'Roxbury Latin School',
    'Horace Mann School',    'Brearley School',
    'Collegiate School',    'Trinity School',
    'Eton College',    'Westminster School',
    "St Paul's School",    "Haberdashers' School",
    'Tonbridge School',    'Winchester College',
    'Rugby School',    'Marlborough College',
    'Dulwich College',    'Stowe School',
    'Scarborough College',    'UWC Atlantic',
    'Harrow School',    'Clifton College',
    'Sevenoaks School',    'Wellington College',
    'Ayb School',    'UWC Dilijan',
    'Quantum College',
    'Shirakatsy Lyceum',
    'PhysMath School',];

  final List<String> academics = [
  "Biological Sciences",
  "Computer Science",
  "Engineering",
  "Humanities",
  "Mathematics",
  "Physical Sciences",
  "Social Sciences",
  "Undecided"];

  final List<String> subjects = [
  "African and African American Studies",
  "Anthropology",
  "Applied Mathematics",
  "Art, Film, and Visual Studies",
  "Astrophysics",
  "Biomedical Engineering",
  "Chemical and Physical Biology",
  "Chemistry",
  "Chemistry and Physics",
  "Classics",
  "Comparative Literature",
  "Computer Science",
  "Earth and Planetary Sciences",
  "East Asian Studies",
  "Economics",
  "Electrical Engineering",
  "Engineering Sciences",
  "English",
  "Environmental Science and Engineering",
  "Environmental Science and Public Policy",
  "Folklore and Mythology",
  "Germanic Languages and Literatures",
  "Government",
  "History",
  "History and Literature",
  "History and Science",
  "History of Art and Architecture",
  "Human Development and Regenerative Biology",
  "Human Evolution Biology",
  "Integrative Biology",
  "Linguistics",
  "Mathematics",
  "Mechanical Engineer",
  "Molecular and Cellular Biology",
  "Music",
  "Near Eastern Languages and Civilizations",
  "Neuroscience",
  "Philosophy",
  "Physics",
  "Psychology",
  "Religion",
  "Romance Languages and Literatures",
  "Slavic Languages and Literatures",
  "Social Studies",
  "Sociology",
  "South Asian Studies",
  "Special Concertation",
  "Statistics",
  "Theater, Dance, and Media",
  "Women, Gender, and Sexuality"
];

final List<String> clubCategories = [
  "Academic",
  "Art",
  "Athletics: Club",
  "Athletics: JV/Varsity",
  "Career Oriented",
  "Community Service (Volunteer)",
  "Computer/Technology",
  "Cultural",
  "Dance",
  "Debate/Speech",
  "Environmental",
  "Family Responsibilities",
  "Foreign Exchange",
  "Foreign Language",
  "Internship",
  "Journalism/Publication",
  "Junior R.O.T.C.",
  "LGBT",
  "Music: Instrumental",
  "Music: Vocal",
  "Religious",
  "Research",
  "Robotics",
  "School Spirit",
  "Science/Math",
  "Social Justice",
  "Student Govt./Politics",
  "Theatre/Drama",
  "Work (Paid)",
  "Other Club/Activity"
];

List<String> countryList = [    'Afghanistan',
    'Albania',    'Algeria',
    'Andorra',    'Angola',
    'Antigua & Deps',    'Argentina',
    'Armenia',
    'Australia',    'Austria',
    'Azerbaijan',    'Bahamas',
    'Bahrain',    'Bangladesh',
    'Barbados',
    'Belarus',    'Belgium',
    'Belize',    'Benin',
    'Bhutan',    'Bolivia',
    'Bosnia Herzegovina',    'Botswana',
    'Brazil',    'Brunei',
    'Bulgaria',    'Burkina',
    'Burundi',    'Cambodia',
    'Cameroon',    'Canada',
    'Cape Verde',    'Central African Rep',
    'Chad',    'Chile',
    'China',    'Colombia',
    'Comoros',    'Congo',
    'Congo {Democratic Rep}',    'Costa Rica',
    'Croatia',    'Cuba',
    'Cyprus',    'Czech Republic',
    'Denmark',    'Djibouti',
    'Dominica',    'Dominican Republic',
    'East Timor',    'Ecuador',
    'Egypt',    'El Salvador',
    'Equatorial Guinea',    'Eritrea',
    'Estonia',    'Ethiopia',
    'Fiji',    'Finland',
    'France',    'Gabon',
    'Gambia',    'Georgia',
    'Germany',    'Ghana',
    'Greece',
    'Grenada',    'Guatemala',
    'Guinea',    'Guinea-Bissau',
    'Guyana',    'Haiti',
    'Honduras',    'Hungary',
    'Iceland',    'India',
    'Indonesia',    'Iran',
    'Iraq',    'Ireland {Republic}',
    'Israel',    'Italy',
    'Ivory Coast',    'Jamaica',
    'Japan',    'Jordan',
    'Kazakhstan',    'Kenya',
    'Kiribati',    'Korea North',
    'Korea South',    'Kosovo',
    'Kuwait',    'Kyrgyzstan',
    'Laos',    'Latvia',
    'Lebanon',    'Lesotho',
    'Liberia',    'Libya',
    'Liechtenstein',    'Lithuania',
    'Luxembourg',    'Macedonia',
    'Madagascar',    'Malawi',
    'Malaysia',    'Maldives',
    'Mali',    'Malta',
    'Marshall Islands',    'Mauritania',
    'Mauritius',    'Mexico',
    'Micronesia',    'Moldova',
    'Monaco',    'Mongolia',
    'Montenegro',    'Morocco',
    'Mozambique',    'Myanmar, {Burma}',
    'Namibia',    'Nauru',
    'Nepal',    'Netherlands',
    'New Zealand',    'Nicaragua',
    'Niger',    'Nigeria',
    'Norway',    'Oman',
    'Pakistan',    'Palau',
    'Panama',    'Papua New Guinea',
    'Paraguay',    'Peru',
    'Philippines',    'Poland',
    'Portugal',    'Qatar',
    'Romania',    'Russian Federation',
    'Rwanda',    'St Kitts & Nevis',
    'St Lucia',    'Saint Vincent & the Grenadines',
    'Samoa',    'San Marino',
    'Sao Tome & Principe',    'Saudi Arabia',
    'Senegal',    'Serbia',
    'Seychelles',    'Sierra Leone',
    'Singapore',    'Slovakia',
    'Slovenia',    'Solomon Islands',
    'Somalia',    'South Africa',
    'South Sudan',    'Spain',
    'Sri Lanka',    'Sudan',
    'Suriname',    'Swaziland',
    'Sweden',    'Switzerland',
    'Syria',    'Taiwan',
    'Tajikistan',    'Tanzania',
    'Thailand',    'Togo',
    'Tonga',    'Trinidad & Tobago',
    'Tunisia',    'Turkey',
    'Turkmenistan',    'Tuvalu',
    'Uganda',    'Ukraine',
    'United Arab Emirates',    'United Kingdom',
    'United States',    'Uruguay',
    'Uzbekistan',    'Vanuatu',
    'Vatican City',    'Venezuela',
    'Vietnam',    'Yemen',
    'Zambia',    'Zimbabwe',
];

}